CREATE TABLE SITES
(SiteID INT PRIMARY KEY IDENTITY(1,1),
SiteNumber VARCHAR(30),
SiteName VARCHAR(30),
Country VARCHAR(30),
PhoneNumber VARCHAR(30))

CREATE TABLE PATIENTS
(PatientID INT PRIMARY KEY IDENTITY(1,1),
PatientCode VARCHAR(30),
SiteID INT FOREIGN KEY REFERENCES Sites(SiteID),
PatientStatus VARCHAR(30),
DATE_RANDOMIZED DATE,
DATE_DROPOUT DATE)

CREATE TABLE RANDOMIZATION
(
RandomizationID INT PRIMARY KEY IDENTITY(1,1),
RandomizationNumber VARCHAR(30),
PatientID INT FOREIGN KEY REFERENCES Patients(PatientID),
BlockID INT,
TreatmentGroup INT
)

CREATE TABLE MATERIALS
(
MaterialID INT PRIMARY KEY IDENTITY(1,1),
KitNumber VARCHAR(30),
MaterialTypeID INT FOREIGN KEY REFERENCES Patients(PatientID),
PatientID INT
)